### PR TITLE
Add Iteration 1 features

### PR DESCRIPTION
**Pull request by Pawat-Sarnchawanakit**
### Features
1. Spell upload
2. Spell view
3. All spells list

### CODE REVIEW

**Comment by jee-gamer** [comment]
Upload Doesn't work for me.
I click upload and get page with red text

image

**Comment by Pawat-Sarnchawanakit** [comment]
That seems to happen when you didn't log in first.
Ima make it redirect to login and add check on the API

**Comment by jee-gamer** [comment]
I think we should have log in and log out button.
It's impossible to log out right now.

**Comment by jee-gamer** [comment]
Right now Upload works fine but I think you should at least force the user to type the name of the spell.
I can just upload nothing as a spell right now.

**Comment by Pawat-Sarnchawanakit** [comment]
Yeah we'll do that.

**Comment by jee-gamer** [comment]
Looks good to me, you can have the final view before you merge.

**Pull request merged**
